import Vue from "vue";
import { 
    Button, 
    Loading,
    Message,
    Select,
    Option,
    Divider,
    Dropdown,
    DropdownMenu,
    DropdownItem,
    Form,
    FormItem,
    Input,
    Breadcrumb,
    BreadcrumbItem,
    Container,
    Aside,
    Main,
    Menu,
    MenuItem,
    Submenu,
    Radio,
    RadioGroup,
    Row,
    Col,
    Dialog,
    Upload,
    Card,
    Steps,
    Step,
    Table,
    TableColumn,
    Pagination,
    MessageBox,
    Switch,
    DatePicker
} from "element-ui";

Vue.use(Button)
    .use(Select)
    .use(Option)
    .use(Divider)
    .use(Dropdown)
    .use(DropdownItem)
    .use(DropdownMenu)
    .use(Form)
    .use(FormItem)
    .use(Input)
    .use(Breadcrumb)
    .use(BreadcrumbItem)
    .use(Container)
    .use(Aside)
    .use(Main)
    .use(Menu)
    .use(MenuItem)
    .use(Submenu)
    .use(Radio)
    .use(RadioGroup)
    .use(Col)
    .use(Row)
    .use(Dialog)
    .use(Upload)
    .use(Card)
    .use(Step)
    .use(Steps)
    .use(Table)
    .use(TableColumn)
    .use(Pagination)
    .use(Switch)
    .use(DatePicker)
    .use(Loading.directive);
Vue.prototype.$loading = Loading.service;
Vue.prototype.$message=Message
Vue.prototype.$confirm=MessageBox.confirm